# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

strategy:
  matrix:
    linux_node_8_x:
      imageName: 'ubuntu-latest'
      node_version: 8.x
    linux_node_10_x:
      imageName: 'ubuntu-latest'
      node_version: 10.x
    mac_node_8_x:
      imageName: 'macos-10.13'
      node_version: 8.x
    mac_node_10_x:
      imageName: 'macos-10.13'
      node_version: 10.x
    windows_node_8_x:
      imageName: 'vs2017-win2016'
      node_version: 8.x
    windows_node_10_x:
      imageName: 'vs2017-win2016'
      node_version: 10.x

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm run test
  displayName: 'npm install, lint and test'
